# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cbd6d2b32f131e28d849a6010857172887eb7e4a4d9573db194bd6424e0532085de311a7a7008f942ee7c939b13b5f01113836a2de4c1d19ffce9f67d42e756

test:
  secret_key_base: d0d24b554f26cdc8cefdf48c13bd97f323461adfd78b5d600c8b19fd3f723a53b582e00893f58322c1a207b803a44c83c181e1c0094c8b789eb892ff6bc344ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
